apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgBnXz4TgZoksnM7gbZryYV6Y7YbjT7ek/1TCfc5/QDEBkTT8GHVoQGrhvACgKDYskMGUvYArNKzekuXxxVRUgsGpk2xYl8m5341gSF7Bn4sKsAVRK+kRWxorUIvjH8zO2/Q7awxCj1Gp3HyHyxuSQ7uuvlNkdxxuYu7ZaT6lw6HVfL/CH6fe728IcEt9FsyeiMD2jZvaQHyFp3/XSlvjuBN+HZpi3DqVR5fpHlwpsctsEMEioTDQJCxR8JAPLH5+ZUmAAege4fptOkqVvKvL0bo+uB7BNrbFBUpozmnkdOTSAGEWFMgvAge9pdDdhUbkFVHNaeoS813iT+J5lpLbvcKvIJ5rjXAQCVFzyGvB24hFImQfGwbqq1yfABy6iwwlHjqqYsHI/klAfFLTQgrfR4+YliYJ8SmAHBTPvurIOV196envtgbvic1qN/8eIfRWemqpAgBwa8KzdWep7xBV4wuuQdC5Iez2vUPGJtMjQk/9iSBXeyUzjyJPs0iiYMLeLe1ncKi6MNXwcXMFAFRiUiu0MBjTso5NCZ/W5+ReutKFSDF3hWyDdHbX1aXmvr5VM5F7P5I1Z+zJ3abuM7D/rPWWoGfSxHzhKHuuoXE+vIcC/Z0sxWxYSttlQITwJjzIZ0JXTSA9LssgCADAQR/VJWiD+iJeJuFxmy0cu5IZFTF0IpJQI1WdKXqNwURC0G2AsddDau+pXKIYpIbyK80PbhzuFrz
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default

