apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgDDIOZal4dCSkSv4x7PImvdko6+x+s4SSNn51nONVv2MBdkd/P3DDf1Tf/qMeQwnZLONtvnJQnT8prM9+5Z6pj0O2t3zNFuoopq1GwvPfNI4oGwzd6TZVg1Fek+7uKQ0AJeWaO62T3EyFb52Q1K+5Ct1RpcWOmrO/ZqjH1/gF77uUVHhSimLYELN6YYWTvS2wTDWPDm0vWQjIhrARvId0/DEBnYafvYTHZ7/tVdeqfe9ND0begPK7KYPDRIWRrsVf88stRL59IXYZZBp0ivDjYHV+MmbUCUKCTe6zpAm2gPEevlp9ZL64UdWqg5StVK3VmDwlt73zBq81QzOk9ea1A6r+1KgVLSrrhcG/jQL94oeGRpBVyMoLdvkY3/g6OSjKUl4PUy0cPywy7P4r0W4dvj44tolnxRCsT96sgfbdkRsQrFvpxkizdgoca54AXrXdDBTPXdxxfcLNgPWAEim9/VnetpddPxDeV4RfMRWh3xBpd/WFmq3DmISwn16vARAb9fnd9sWBohxCUGWlLVt6clEE/6a8nQZsl7aP1fZPtN+5ADAmgOFk5kdIcMBOlXbzMxXLN8tvFoz99Z/dh848KMURLE/rEBWPXcsNy1bIc7A68r//P/BnzBzXgm6IfnR83cmgmTmC89B7oBcC09cwf0GiR4cuR7ME1Cgo8hLAj9nCBZ1ct7XBmWPTvnT39U0PIve0Gac6CqWacvLQJkNR8AtMwiOSBUHZ3qlS4pM6mTV/iGsej4PDjMKri4Gwja3gvErg==
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default

